spring:
  application:
    name: OrderService
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      configserver:http://localhost:9296

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
 #   register-with-eureka: true
 #   service-url:
 #     defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
